// examples/vue-dynamic/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import './style.css'
import { createSwapy, SlotItemMapArray, Swapy, utils } from '../../src';

type Item = {
  id: string
  title: string
}

const initialItems: Item[] = [
  { id: '1', title: '1' },
  { id: '2', title: '2' },
  { id: '3', title: '3' },
]

const container = ref<HTMLElement | null>()
const swapy = ref<Swapy | null>(null)
const items = ref(initialItems)
const id = ref(4)

const slotItemMap = ref<SlotItemMapArray>([...utils.initSlotItemMap(items.value, 'id')])
watch(items, () =>
  utils.dynamicSwapy(swapy.value, items.value, 'id', slotItemMap.value, (value: SlotItemMapArray) => slotItemMap.value = value),
  { deep: true }
)
const slottedItems = computed(() => utils.toSlottedItems(items.value, 'id', slotItemMap.value))


onMounted(() => {
  if (container.value) {
    swapy.value = createSwapy(container.value, {
      manualSwap: true,
      // animation: 'dynamic'
      // autoScrollOnDrag: true,
      // swapMode: 'drop',
      // enabled: true,
      // dragAxis: 'x',
      // dragOnHold: true
    })
    swapy.value.onSwap(event => {
      requestAnimationFrame(() => {
        slotItemMap.value = event.newSlotItemMap.asArray
      })
    })
  }
})

onUnmounted(() => {
  swapy.value?.destroy()
})
</script>

<template>
  <div class="container"
    ref="container">
    <div class="items">
      <div class="slot"
        v-for="{ slotId, itemId, item } in slottedItems"
        :key="slotId"
        :data-swapy-slot="slotId">
        <div v-if="item"
          class="item"
          :data-swapy-item="itemId"
          :key="itemId">
          <span>{{ item.title }}</span>
          <span class="delete"
            data-swapy-no-drag
            @click="() => {
              items = items.filter(i => i.id !== item.id)
            }"></span>
        </div>
      </div>
    </div>
    <div class="item item--add"
      @click="() => {
        const newItem: Item = { id: `${id}`, title: `${id}` }
        items.push(newItem)
        id++
      }">+</div>
  </div>
</template>

// examples/svelte-dynamic/App.svelte
<script lang="ts">
  import {
    createSwapy,
    type SlotItemMapArray,
    type Swapy,
    utils
  } from '../../src'
  import { onDestroy, onMount, untrack } from 'svelte'
  import './style.css'

  let container: HTMLElement
  let swapy: Swapy | null = null

  type Item = {
    id: string
    title: string
  }

  const initialItems: Item[] = [
    { id: '1', title: '1' },
    { id: '2', title: '2' },
    { id: '3', title: '3' }
  ]

  let items = $state(initialItems)
  let id = $state(4)

  let slotItemMap = $state(utils.initSlotItemMap(initialItems, 'id'))
  let slottedItems = $derived(utils.toSlottedItems(items, 'id', slotItemMap))

  let setSlotItemMap = (value: SlotItemMapArray) => (slotItemMap = value)

  $effect(() => {
    utils.dynamicSwapy(
      swapy,
      items,
      'id',
      untrack(() => slotItemMap),
      setSlotItemMap
    )
  })

  onMount(() => {
    if (container) {
      swapy = createSwapy(container, {
        manualSwap: true
        // animation: 'dynamic'
        // autoScrollOnDrag: true,
        // swapMode: 'drop',
        // enabled: true,
        // dragAxis: 'x',
        // dragOnHold: true
      })

      swapy.onSwapStart((event) => {
        console.log('start', event)
      })

      swapy.onSwap((event) => {
        requestAnimationFrame(() => {
          slotItemMap = event.newSlotItemMap.asArray
        })
      })

      swapy.onSwapEnd((event) => {
        console.log('end', event)
      })
    }
  })

  onDestroy(() => {
    swapy?.destroy()
  })
</script>

<div class="container" bind:this={container}>
  <div class="items">
    {#each slottedItems as { slotId, itemId, item }}
      {#key slotId}
        <div class="slot" data-swapy-slot={slotId}>
          {#if item}
            {#key itemId}
              <div class="item" data-swapy-item={itemId}>
                <span>{item.title}</span>
                <button
                  aria-label="delete"
                  class="delete"
                  data-swapy-no-drag
                  onclick={() => {
                    items = items.filter((i) => i.id !== item.id)
                  }}
                ></button>
              </div>
            {/key}
          {/if}
        </div>
      {/key}
    {/each}
  </div>
  <button
    class="item item--add"
    onclick={() => {
      const newItem: Item = { id: `${id}`, title: `${id}` }
      items.push(newItem)
      id++
    }}>+</button
  >
</div>
